var navigation = "<div class=\"navigation\">"
		+ "<ul>"
		+ "<li><a class=\"a\">TOOLS<span class=\"arrow\"></span></a>"
		+ "<ul>"
		+ "<li><a href=\"../qrcode/qrcode.html\">QRCode</a></li>"
		+ "<li><a href=\"../fx/fx.html\">Math function</a></li>"
		+ "</ul>"
		+ "</li>"
		+ "<li><a class=\"a\">GAMES<span class=\"arrow\"></span></a>"
		+ "<ul>"
		+ "<li><a href=\"../snake/snake.html\">SNAKE</a></li>"
		+ "<li><a href=\"../quadraticCurve/quadraticCurve.html\">Curve</a></li>"
		+ "<li><a href=\"../ball/ball.html\">BALLS</a></li>"
		+ "</ul>"
		+ "</li>"
		+ "<li><a class=\"a\">STYLES<span class=\"arrow\"></span></a>"
		+ "<ul>"
		+ "<li><a href=\"../books/s1/s1.html\">毁一生</a></li>"
		+ "<li><a href=\"../typewriter/tw.html\">Typewriter</a></li>"
		+ "<li><a href=\"../welcome/welcome.html\">WELCOME</a></li>"
		+ "</ul>"
		+ "</li>"
		+ "<li class=\"right a\"><a href=\"../../index.html\" style=\"width:30px;\"><img src=\"../../res/vivaxy.jpg\" height=\"30px\"></a></li>"
		+ "</ul>"
		+ "</div>";
document.write(navigation);